appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: JT07VhFMIIr+efUo6DKj/5Hh2jjzLflTPUjQVRp5RmGpAx1rtydOBNCti/dJVfFZe65gPinEHOm4p74S0H0EnpNYqx8+BQrOziRtcwOZ50BTZW4x9Eo/jzboJQf5I3w63Qe5I5Zyy8urn+e4XBfrR5ai1FrtOw0pCyUWv6ZwBcVaEu2uehhqjyK8tjdb+64mtxMENqINwNDchTHXbI+RXaEqn+v9HBM0eytaffdlPmXQL3dLtnmYQyaDoiWAt+2ev9BrRQEZO/TXL593oABEL5Q3QWcATSb3sawf+Ax6IUinNniIFFQyd/gb63FQ97a93tOJpnuagMf03+Go4V26XQp93nFZiVHqLOrALtYE+JCb+ARjS0SUonALTpYFzjRw0tt85smGrMev/fOkWyRbcSylRBhm3yIgKXdUBn2xfQPl7YfKJrfPQwtvn5cAv0pESuk+UDzazwNGbk5ww0zowSUoSEQhOapU136ch/ppIQnxAVvs58D9KVjAMJA/9ZCSITg8eu+I9Lff61XTVWa3XB721Nyw9bsDaxKJV/FqjK4M1WP/chUyIGMaqiqvD+QTpJYfKPPn6frj/UFmGvNEHrhYrHd3L5YJU3MFjpR7FiEuDABwzvTK59wrJYb3ZlFI8XbCyy0/0m5OY1wuyGFBKgEMmuTxqj5dVpo42abBelI=}
provider:
  win: azure
bot:
  automerge: true
